/*An Entity is a class that represents a table in your database. 
 * In this case, the Book class is mapped to a database table called Book. Each instance of Book represents a row in that table.
*/



package com.book.store.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;

@Entity
public class Book { /*   This Book class is a JPA (Java Persistence API) entity that represents the data
                         model for a book in the application. The class maps to a database table, where each instance 
                         of Book corresponds to a row in that table.
                        */

	@Id        //  Marks the id field as the primary key for the entity.
	@GeneratedValue(strategy=GenerationType.IDENTITY)   /*  Indicates that the primary key value is auto-generated by the database
	                                                        The IDENTITY strategy typically relies on an auto-incrementing column.
	                                                    */
	private int id;
	private String name;
	private String author;
	private String price;
//	@Lob
//	private byte [] pdfContent;
//	private String pdfContentType;
	
	/*This is a parameterized constructor for the class Book. 
	 * It's used to create a Book object with all the properties (id, name, author, and price) initialized when the object is created.
	 */
	public Book(int id, String name, String author, String price) {
		super();
		this.id = id;
		this.name = name;
		this.author = author;
		this.price = price;
		}
	
	/*This is the default constructor of the Book class. 
	 * It doesn’t take any parameters and is often required by frameworks like Spring, Hibernate, or JPA to instantiate 
	 * objects via reflection.
	 * 
	 */
	
	public Book() {  
		super();
	}
	
	
	/*  Java requires getters and setters for the JPA provider (like Hibernate) to access and manage the entity properties.
	 *  You can use Lombok (@Getter, @Setter) to avoid writing them manually.
	  */
	 
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAuthor() {
		return author;
	}
	public void setAuthor(String author) {
		this.author = author;
	}
	
	public String getPrice() {
		return price;
	}
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * @return the pdfContent
	 */
//	public byte[] getPdfContent() {
//		return pdfContent;
//	}

	/**
	 * @param pdfContent the pdfContent to set
	 */
//	public void setPdfContent(byte[] pdfContent) {
//		this.pdfContent = pdfContent;
//	}
//
//	/**
//	 * @return the pdfContentType
//	 */
//	public String getPdfContentType() {
//		return pdfContentType;
//	}
//
//	/**
//	 * @param pdfContentType the pdfContentType to set
//	 */
//	public void setPdfContentType(String pdfContentType) {
//		this.pdfContentType = pdfContentType;
//	}
	
	
	
}
